---
name: WebService-Etsy
version: 0.2
author:
  - Ian Malpass (ian-cpan@indecorous.com)
abstract: Access the Etsy REST API.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  JSON: 2.0
  LWP::UserAgent: 2.0
build_requires:
  Test::More: 0
provides:
  WebService::Etsy:
    file: lib/WebService/Etsy.pm
    version: 0.2
  WebService::Etsy::Methods:
    file: lib/WebService/Etsy/Methods.pm
  WebService::Etsy::Response:
    file: lib/WebService/Etsy/Response.pm
  WebService::Etsy::Result:
    file: lib/WebService/Etsy/Result.pm
  WebService::Etsy::Result::GiftGuide:
    file: lib/WebService/Etsy/Result.pm
  WebService::Etsy::Result::Int:
    file: lib/WebService/Etsy/Result.pm
  WebService::Etsy::Result::Listing:
    file: lib/WebService/Etsy/Result.pm
  WebService::Etsy::Result::Method:
    file: lib/WebService/Etsy/Result.pm
  WebService::Etsy::Result::Shop:
    file: lib/WebService/Etsy/Result.pm
  WebService::Etsy::Result::String:
    file: lib/WebService/Etsy/Result.pm
  WebService::Etsy::Result::Tag:
    file: lib/WebService/Etsy/Result.pm
  WebService::Etsy::Result::User:
    file: lib/WebService/Etsy/Result.pm
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
